### ISSUE TITLE
申請

### ISSUE THREAD

**Issue by YakushimaruYuki** [OtokonokoUniversity/About#1]
親愛的 Otokonoko 大學：

你好！我志願加入 Otokonoko 大學，現在就成為 Otokonoko！

YakushimaruYuki

**Comment by kaguramiyabiw** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Otokonoko University

**Comment by YakushimaruYuki** [comment]
親愛的 Otokonoko 大學：

I confirmed the offer. 
Thanks a lot!

YakushimaruYuki
