### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by YukariChiba** [OtokonokoUniversity/About#20]
Dear whom may concern,

Hello. I want to join Otokonoko University to study how to become an Otokonoko!

As an aspiring student, I am applying for admission to your college. My research indicates that the Master of Otokonoko program you offers is outstanding, and will provide me with the best training to enter this profession. Your organization has excellent reputation. After the exceptional reviews I received from recent students, I am convinced that this is the best college to pursue my studies in becoming an Otokonoko.

Regards,
@YukariChiba

**Comment by kagurazakamasae** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Otokonoko University
