### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by Aissae** [OtokonokoUniversity/About#6]
亲爱的 Otokonoko 大学：

你好！我志愿加入 Otokonoko 大学，现在就成为 Otokonoko！

你的名字
aisse

**Comment by li8il** [comment]
亲爱的 Otokonoko 大学：

你好！我志愿加入 Otokonoko 大学，现在就成为 Otokonoko！

你的名字
li8il

**Comment by 10086m** [comment]
Dear Otokonoko University,

Hello! I volunteered to join Otokonoko University and now become Otokonoko!

What's your name
10086

**Comment by 10086m** [comment]
Dear Otokonoko University,

Hello! I volunteered to join Otokonoko University and now become Otokonoko!

What's your name
10086m

**Comment by kagurazakamasae** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Otokonoko University
